2025-06-20 00:35:00.645777+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "[*]ID"; 期待されるステートメント "INSERT"
Syntax error in SQL statement "[*]ID"; expected "INSERT"; SQL statement:
ID [42001-232]
2025-06-20 00:38:52.275604+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM CHAT_ROOM ID [*]NAME"
Syntax error in SQL statement "SELECT * FROM CHAT_ROOM ID [*]NAME"; SQL statement:
SELECT * FROM CHAT_ROOM ID NAME [42000-232]
2025-06-20 00:38:58.883697+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "NAME" が見つかりません
Table "NAME" not found; SQL statement:
SELECT * FROM  NAME [42102-232]
2025-06-20 00:39:00.678827+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "NAME" が見つかりません
Table "NAME" not found; SQL statement:
SELECT * FROM NAME [42102-232]
2025-07-07 02:52:24.018795+09:00 jdbc[23]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE CHAT_ROOM [*]USERS"
Syntax error in SQL statement "SELECT * FROM MESSAGE CHAT_ROOM [*]USERS"; SQL statement:
SELECT * FROM MESSAGE CHAT_ROOM USERS [42000-232]
2025-07-07 02:52:39.258319+09:00 jdbc[23]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM USERS CHAT_ROOM [*]MESSAGE"
Syntax error in SQL statement "SELECT * FROM USERS CHAT_ROOM [*]MESSAGE"; SQL statement:
SELECT * FROM USERS CHAT_ROOM MESSAGE [42000-232]
2025-07-07 02:55:53.483914+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"
Syntax error in SQL statement "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"; SQL statement:
SELECT * FROM MESSAGE USERS CHAT_ROOM [42000-232]
2025-07-07 02:55:54.673633+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"
Syntax error in SQL statement "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"; SQL statement:
SELECT * FROM MESSAGE USERS CHAT_ROOM [42000-232]
2025-07-07 02:55:54.854316+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"
Syntax error in SQL statement "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"; SQL statement:
SELECT * FROM MESSAGE USERS CHAT_ROOM [42000-232]
2025-07-07 02:55:55.023367+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"
Syntax error in SQL statement "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"; SQL statement:
SELECT * FROM MESSAGE USERS CHAT_ROOM [42000-232]
2025-07-07 02:55:55.169630+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"
Syntax error in SQL statement "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"; SQL statement:
SELECT * FROM MESSAGE USERS CHAT_ROOM [42000-232]
2025-07-07 02:55:55.394005+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"
Syntax error in SQL statement "SELECT * FROM MESSAGE USERS [*]CHAT_ROOM"; SQL statement:
SELECT * FROM MESSAGE USERS CHAT_ROOM [42000-232]
2025-07-07 02:56:12.044539+09:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "SELECT * FROM CHAT_ROOM NAME [*]ID"
Syntax error in SQL statement "SELECT * FROM CHAT_ROOM NAME [*]ID"; SQL statement:
SELECT * FROM CHAT_ROOM NAME ID [42000-232]
2025-07-17 03:44:03.200866+09:00 jdbc[15]: null
org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
